### ISSUE TITLE
I am unable to commit changes 

### ISSUE THREAD

**Issue by Mujeeb-Ahmed** [Mujeeb-Ahmed/Lecture-0#1]
The error i am getting here is 

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'pc@DESKTOP-VNO7OVP.(none)')

**Comment by Mujeeb-Ahmed** [comment]
I am getting these errors while executing my python file with python manage.py runserver

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x00000116D5CF3D90>
Traceback (most recent call last):
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\urls\resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\pc\dev\cfehome\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\pc\dev\cfehome\mysite\mysite\urls.py", line 20, in <module>
    path('', include('hello.urls')),
  File "C:\Users\pc\dev\cfehome\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\pc\dev\cfehome\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\pc\dev\cfehome\mysite\hello\urls.py", line 1, in <module>
    from python.urls import path
ModuleNotFoundError: No module named 'python'

**Comment by Mujeeb-Ahmed** [comment]
> I am getting these errors while executing my python file with python manage.py runserver
> 
> Unhandled exception in thread started by <function check_errors..wrapper at 0x00000116D5CF3D90>
> Traceback (most recent call last):
> File "C:\Users\pc\dev\cfehome\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
> fn(*args, **kwargs)
> File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
> self.check(display_num_errors=True)
> File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\management\base.py", line 379, in check
> include_deployment_checks=include_deployment_checks,
> File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\management\base.py", line 366, in _run_checks return checks.run_checks(**kwargs) File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks new_errors = check(app_configs=app_configs) File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config return check_resolver(resolver) File "C:\Users\pc\dev\cfehome\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver return check_method() File "C:\Users\pc\dev\cfehome\lib\site-packages\django\urls\resolvers.py", line 396, in check for pattern in self.url_patterns: File "C:\Users\pc\dev\cfehome\lib\site-packages\django\utils\functional.py", line 37, in **get** res = instance.**dict**[self.name] = self.func(instance) File "C:\Users\pc\dev\cfehome\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module) File "C:\Users\pc\dev\cfehome\lib\site-packages\django\utils\functional.py", line 37, in **get** res = instance.**dict**[self.name] = self.func(instance) File "C:\Users\pc\dev\cfehome\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module return import_module(self.urlconf_name) File "C:\Users\pc\dev\cfehome\lib\importlib__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed File "C:\Users\pc\dev\cfehome\mysite\mysite\urls.py", line 20, in path('', include('hello.urls')), File "C:\Users\pc\dev\cfehome\lib\site-packages\django\urls\conf.py", line 34, in include urlconf_module = import_module(urlconf_module) File "C:\Users\pc\dev\cfehome\lib\importlib__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "C:\Users\pc\dev\cfehome\mysite\hello\urls.py", line 1, in 
> from python.urls import path
> ModuleNotFoundError: No module named 'python'

the issue is resolved. Just saved the files in which changes were made.
